ZacSweers/CatchUp

- app/src/main/res/values-de/strings.xml
Added German translations to the strings resources
> Added German translations

- app/src/main/res/values-fr/strings.xml
Added French translations to the strings resources.
I'll be of course willing to help for future translations 😄
> Added French translations to the strings resources

- app/src/main/kotlin/io/sweers/catchup/ui/about/LicensesController.kt
- app/src/main/kotlin/io/sweers/catchup/ui/base/CatchUpItemViewHolder.kt
- app/src/main/res/layout/list_item_general.xml
I've read your complaints about ConstraintLayout and I've been converting lately lots of our legacy layouts to ConstraintLayout, so I thought in giving you a hand.
I tried it in emulator and it looks like this, hope it looks fine.
> Convert list_item_general to use ConstraintLayout

- services/producthunt/src/main/kotlin/io/sweers/catchup/service/producthunt/model/Post.kt
- services/reddit/src/main/kotlin/io/sweers/catchup/service/reddit/model/SampleData.kt
- tooling/moshkt/compiler/src/main/kotlin/io/sweers/moshkt/compiler/MoshKtProcessor.kt
This implements an idea that Ryan and I were talking about, where we create a defaults-only instance first before then copying it with the potentially new values if they're present.
Example code in `Foo`:
```kotlin
@MoshiSerializable
data class Foo(
@Json(name = "first_name") val firstName: String,
@Json(name = "last_name") val lastName: String,
val age: Int,
val nationalities: List<String> = emptyList(),
val weight: Float,
val tattoos: Boolean = false,
val race: String?,
val hasChildren: Boolean = false,
val favoriteFood: String? = null,
val favoriteDrink: String? = "Water"
)
```
Output:
```kotlin
class Foo_JsonAdapter(private val moshi: Moshi) : JsonAdapter<Foo>() {
override fun fromJson(reader: JsonReader): Foo? {
if (reader.peek() == JsonReader.Token.NULL) {
reader.nextNull<Any>()
} …
```
> Default values support in moshkt

- services/reddit/src/main/kotlin/io/sweers/catchup/service/reddit/model/SampleData.kt
- tooling/moshkt/README.md
- tooling/moshkt/compiler/src/main/kotlin/io/sweers/moshkt/compiler/MoshKtProcessor.kt
This creates adapter properties rather than always looking up on a saved moshi property. The properties are kept by their TypeName and not necessarily 1:1 with properties, so we can reuse/share adapters for the same types. Names are simplified to be more human readable (from auto-value-gson).
This also includes a few opportunistic cleanups:
- Use a NameAllocator for all names via allocate() extension fun
- Removed a stale debugging check
- Added a commented note about arrays, which I found out don't currently work yet (albeit they're advised against in data classes)
Source data class:
```Kotlin
@MoshiSerializable
data class Foo(
@Json(name = "first_name") val firstName: String,
@Json(name = "last_name") val lastName: String,
val age: Int,
val nationalities: List<String> = emptyList(),
val …
```
> Implement adapter caching

- app/build.gradle.kts
- app/src/main/kotlin/io/sweers/catchup/ui/FontHelper.kt
- app/src/main/kotlin/io/sweers/catchup/ui/widget/BaselineGridTextView.kt
- util/src/main/kotlin/io/sweers/catchup/util/TimberExt.kt
Only thing I'm not sure about is mixing this with the existing downloadable fonts. It seems to work if I merge them or keep them separate, so I'm just going to keep them separate for now. Couldn't find any public examples of doing both in the same app.
Resolves #115
> Introduce EmojiCompat for use in textviews

- app/build.gradle.kts
I think this is what you were going for?
> Change duplicate kotlin jdk7 dependency to jdk8

- app/src/main/kotlin/io/sweers/catchup/data/CatchUpDatabase.kt
- app/src/main/kotlin/io/sweers/catchup/data/ServiceDao.kt
- app/src/main/kotlin/io/sweers/catchup/ui/fragments/SmmryFragment.kt
- app/src/main/kotlin/io/sweers/catchup/ui/fragments/service/StorageBackedService.kt
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
- libraries/gemoji/src/main/kotlin/io/sweers/catchup/gemoji/GemojiModule.kt
- service-api/src/main/kotlin/io/sweers/catchup/service/api/ImageInfo.kt
- service-api/src/main/kotlin/io/sweers/catchup/service/api/Mark.kt
https://developer.android.com/jetpack/docs/release-notes#october_8_2018
> Update ROOM to 2.1.0-alpha01

- app/src/main/kotlin/io/sweers/catchup/ui/fragments/service/ServiceFragment.kt
Nothing special, just gets rid of a few useless functions
> Use SimplePageStateChangeCallbacks in ServiceFragment

- CHANGELOG.md
- app/src/main/kotlin/io/sweers/catchup/ui/activity/OrderServicesActivity.kt
- app/src/main/res/drawable/ic_arrow_back_black_24dp.xml
- app/src/main/res/drawable/ic_shuffle_black_24dp.xml
- app/src/main/res/layout/fragment_order_services.xml
- app/src/main/res/menu/order_services.xml
- app/src/main/res/values/strings.xml
I thought this would be fun. Then the shuffle button didn't appear. Now I'm not having fun
To test: Run the app, go to settings, go to reorder services. Observe no shuffle button in the toolbar. This is making me feel like my job title of "senior android engineer" is a fraud.
> Add shuffle button to order services

- app/build.gradle.kts
- app/src/main/kotlin/io/sweers/catchup/data/smmry/SmmryModule.kt
- app/src/main/kotlin/io/sweers/catchup/data/smmry/SmmryService.kt
- app/src/main/kotlin/io/sweers/catchup/injection/ServiceDisplayBindingModule.kt
- app/src/main/kotlin/io/sweers/catchup/ui/fragments/SmmryFragment.kt
- app/src/main/kotlin/io/sweers/catchup/util/coroutines/LifecycleOwnerScope.kt
- app/src/main/kotlin/io/sweers/catchup/util/coroutines/LifecycleScoper.kt
- build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
This brings in coroutines via the `Smmry` API, leveraging them on both retrofit as well as ROOM
> Introduce coroutines (via Smmry)

- app/build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
As described in the large gradle projects I/O talk
> Use lazy configuration for version name and code

- app/build.gradle.kts
- app/lint.xml
- libraries/gemoji/build.gradle.kts
- service-api/build.gradle.kts
- service-registry/service-registry/build.gradle.kts
- services/designernews/build.gradle.kts
- services/dribbble/build.gradle.kts
- services/github/build.gradle.kts
- services/hackernews/build.gradle.kts
- services/imgur/build.gradle.kts
- services/medium/build.gradle.kts
- services/newsapi/build.gradle.kts
- services/producthunt/build.gradle.kts
- services/reddit/build.gradle.kts
- services/slashdot/build.gradle.kts
- services/unsplash/build.gradle.kts
- services/uplabs/build.gradle.kts
Uses checkDependencies and (best effort) disables lintin in non-app modules
> Fix lint wiring

- gradle.properties
This is on by default.
See: https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon
> Remove 'org.gradle.daemon=true'

- app/build.gradle.kts
- libraries/gemoji/build.gradle.kts
- service-api/build.gradle.kts
- service-registry/service-registry-compiler/build.gradle.kts
- service-registry/service-registry/build.gradle.kts
- services/designernews/build.gradle.kts
- services/dribbble/build.gradle.kts
- services/github/build.gradle.kts
- services/hackernews/build.gradle.kts
- services/imgur/build.gradle.kts
- services/medium/build.gradle.kts
- services/newsapi/build.gradle.kts
- services/producthunt/build.gradle.kts
- services/reddit/build.gradle.kts
- services/slashdot/build.gradle.kts
- services/unsplash/build.gradle.kts
- services/uplabs/build.gradle.kts
> Remove buildcache = true, since it is true by default

- build.gradle.kts
- libraries/tooling/spi-visualizer/build.gradle.kts
> Clean up some build files

- app/build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
- libraries/gemoji/build.gradle.kts
- libraries/util/build.gradle.kts
- service-api/build.gradle.kts
- service-registry/service-registry/build.gradle.kts
- services/designernews/build.gradle.kts
- services/dribbble/build.gradle.kts
- services/github/build.gradle.kts
- services/hackernews/build.gradle.kts
- services/imgur/build.gradle.kts
- services/medium/build.gradle.kts
- services/newsapi/build.gradle.kts
- services/producthunt/build.gradle.kts
- services/reddit/build.gradle.kts
- services/slashdot/build.gradle.kts
- services/unsplash/build.gradle.kts
- services/uplabs/build.gradle.kts
> Remove 'buildToolsVersion'

- app/src/debug/kotlin/io/sweers/catchup/flipper/FlipperModule.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/MainActivity.kt
- buildSrc/src/main/kotlin/dependencies.kt
- libraries/tooling/spi-visualizer/src/main/java/io/sweers/catchup/spivisualizer/BindingGraphVisualizer.java
Not sure why the versions plugin misses this
> Update dagger to 2.23.2

- app/src/main/kotlin/io/sweers/catchup/ui/activity/MainActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/fragments/service/ServiceFragment.kt
- buildSrc/src/main/kotlin/dependencies.kt
[InboxRecyclerView v2.0.0-beta1](https://github.com/saket/InboxRecyclerView/releases/tag/v2.0.0-beta1) 🎊
> Update InboxRecyclerView to v2.0.0-beta1

- README.md
- app/build.gradle.kts
- app/src/debug/kotlin/io/sweers/catchup/app/DebugApplicationModule.kt
- app/src/debug/kotlin/io/sweers/catchup/data/VariantDataModule.kt
- app/src/debug/kotlin/io/sweers/catchup/flipper/FlipperModule.kt
- buildSrc/src/main/kotlin/dependencies.kt
- gradle.properties
Resolves #94 
I got a bunch of work done integrating more of Flipper before realizing I'd already done most of it a long time ago 🤦‍♂️
> Remove stetho, move entirely to Flipper

- app/src/main/kotlin/io/sweers/catchup/ui/activity/ImageViewerActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/widget/ZoomableGestureImageView.kt
- app/src/main/res/values/dimen.xml
- buildSrc/src/main/kotlin/dependencies.kt
Trying out a simpler way to setup Flick. Seems to be working fine with CatchUp.
> Bump Flick to v1.7.0

- README.md
The medium article has been moved to Zac's personal blog. Updating link to save users a click.
> Update article link

- app/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/CatchUpPlugin.kt
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/VersionCodeTask.kt
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/VersionNameTask.kt
Based on https://github.com/ducrohet/versionCode-4.0-sample
> Switch to new APIs for versioning in AGP

- buildSrc/src/main/kotlin/dependencies.kt
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/CatchUpPlugin.kt
> OkHttp bom v2

- .github/workflows/ci.yml
- .github/workflows/stats.yml
- app/build.gradle.kts
- app/proguard-rules.pro
- app/src/debug/res/layout/bugreport_view.xml
- app/src/debug/res/layout/debug_view_content.xml
- app/src/main/kotlin/io/sweers/catchup/ui/about/AboutActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/SettingsActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/fragments/service/ServiceFragment.kt
- app/src/main/kotlin/io/sweers/catchup/util/PrecomputedTextSetterCompat.kt
- app/src/main/kotlin/io/sweers/catchup/util/customtabs/CustomTabsHelper.kt
- app/src/main/res/layout/fragment_about.xml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/CatchUpPlugin.kt
- libraries/tzdata/src/main/java/com/gabrielittner/threetenbp/LazyZoneRulesProvider.java
- services/designernews/src/main/kotlin/io/sweers/catchup/service/designernews/DesignerNewsService.kt
- services/dribbble/src/main/kotlin/io/sweers/catchup/service/dribbble/DribbbleService.kt
- services/github/src/main/kotlin/io/sweers/catchup/service/github/GitHubService.kt
- services/hackernews/src/main/kotlin/io/sweers/catchup/service/hackernews/HackerNewsService.kt
- services/hackernews/src/main/kotlin/io/sweers/catchup/service/hackernews/model/HNType.kt
- services/medium/src/main/kotlin/io/sweers/catchup/service/medium/MediumService.kt
- services/producthunt/src/main/kotlin/io/sweers/catchup/service/producthunt/ProductHuntService.kt
- services/reddit/src/main/kotlin/io/sweers/catchup/service/reddit/RedditService.kt
- services/reddit/src/main/kotlin/io/sweers/catchup/service/reddit/model/RedditObjectFactory.kt
- services/slashdot/src/main/AndroidManifest.xml
- services/slashdot/src/main/kotlin/io/sweers/catchup/service/slashdot/SlashdotService.kt
- services/unsplash/src/main/kotlin/io/sweers/catchup/service/unsplash/UnsplashService.kt
- services/uplabs/src/main/kotlin/io/sweers/catchup/service/uplabs/UplabsService.kt
Lint cleanups, warnings, and added a stats.yml for PR stats
> Misc build tweaks

- app/src/main/kotlin/io/sweers/catchup/ui/activity/MainActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/OrderServicesActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/ServiceSettingsActivity.kt
- service-registry/service-registry-compiler/src/main/kotlin/io/sweers/catchup/serviceregistry/compiler/ServiceRegistryCompiler.kt
- service-registry/service-registry/build.gradle.kts
Nicely cleans up a bit of the manual wiring
> Use InstallIn for service compiler

- service-registry/service-registry-compiler/build.gradle.kts
- service-registry/service-registry-compiler/src/main/kotlin/io/sweers/catchup/serviceregistry/compiler/ServiceRegistryCompiler.kt
Because kapt doesn't support multiple rounds with generated kotlin code :(
> Switch service registry compiler to generate java

- .github/workflows/ci.yml
- app/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/CatchUpPlugin.kt
- gradle/wrapper/gradle-wrapper.properties
Disabling bugsnag and play publisher for now - not publishing anytime soon and needs work
> Update all the things

- .github/workflows/ci.yml
- app/build.gradle.kts
- app/src/main/kotlin/io/sweers/catchup/app/ApplicationModule.kt
- app/src/main/kotlin/io/sweers/catchup/data/GithubApolloModule.kt
- app/src/main/kotlin/io/sweers/catchup/ui/about/ChangelogFragment.kt
- app/src/main/kotlin/io/sweers/catchup/ui/about/LicensesFragment.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/ImageViewerActivity.kt
- app/src/main/kotlin/io/sweers/catchup/ui/fragments/service/ImageAdapter.kt
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/dependencies.kt
- buildSrc/src/main/kotlin/dev/zacsweers/catchup/gradle/CatchUpPlugin.kt
- gradle/wrapper/gradle-wrapper.properties
- libraries/smmry/build.gradle.kts
- services/github/src/main/kotlin/io/sweers/catchup/service/github/GitHubService.kt
~Waiting for an anvil update due to some bugs~
Finally ready to go build-wise but now studio instantly stackoverflows trying to load this https://issuetracker.google.com/issues/209180675
> Kotlin 1.6, Gradle 7.3, AGP 7.2.0-alpha05, JDK 17, misc other updates

- .github/workflows/ci.yml
- app/build.gradle.kts
- app/src/main/kotlin/dev/zacsweers/catchup/service/CatchUpViewModelProviderFactory.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/CircuitModule.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/ServiceScreen.kt
- gradle/libs.versions.toml
- libraries/tooling/spi-multibinds-validator/src/main/kotlin/dev/zacsweers/catchup/spi/multibinds/MultibindsValidator.kt
> Update to Circuit 0.5.0

- app/src/main/kotlin/io/sweers/catchup/ui/about/AboutScreen.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/OrderServicesActivity2.kt
- libraries/compose-extensions/src/main/kotlin/dev/zacsweers/catchup/compose/DragAndDrop.kt
[untitled.webm](https://user-images.githubusercontent.com/1361086/211180085-3fb096c4-74fc-48cf-b363-a9ac414229da.webm)
> Implement drag and drop in order services activity

- app/src/main/kotlin/io/sweers/catchup/ui/activity/SettingsScreen.kt
- app/src/main/res/values/strings.xml
- libraries/compose-extensions/src/main/kotlin/dev/zacsweers/catchup/compose/DisableableContent.kt
Haven't covered the debug drawer yet because I can't use it due to M3 1.1.0 alphas being binary incompatible with compose alphas 🙃
> Implement DisableableContent for settings screen

- app/src/main/kotlin/dev/zacsweers/catchup/service/ContentTypeChecker.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/ServiceMediator.kt
They're too slow! Just do superficial checks for now
> Remove HEAD checks for content types

- app/build.gradle.kts
- app/src/main/assets/generated_licenses.json
- gradle/libs.versions.toml
- services/slashdot/build.gradle.kts
- services/slashdot/src/main/kotlin/io/sweers/catchup/service/slashdot/Entry.kt
- services/slashdot/src/main/kotlin/io/sweers/catchup/service/slashdot/Feed.kt
- services/slashdot/src/main/kotlin/io/sweers/catchup/service/slashdot/Link.kt
- services/slashdot/src/main/kotlin/io/sweers/catchup/service/slashdot/SlashdotService.kt
- services/slashdot/src/test/kotlin/io/sweers/catchup/service/slashdot/FeedTest.kt
> Remove tikxml

- app/src/main/kotlin/dev/zacsweers/catchup/service/ServiceScreen.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/TextServiceUi.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/VisualServiceUi.kt
- app/src/main/kotlin/io/sweers/catchup/home/HomeScreen.kt
- config/lint/lint.xml
- libraries/compose-extensions/src/main/kotlin/dev/zacsweers/catchup/compose/ScrollToTop.kt
- services/github/src/main/kotlin/io/sweers/catchup/service/github/GitHubTrendingParser.kt
Resolves #770. Not using a modifier at all per advice elsewhere
> Implement ScrollToTop

- app/src/main/kotlin/dev/zacsweers/catchup/circuit/IntentScreen.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/ServiceScreen.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/ServiceUiCommon.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/TextServiceUi.kt
- app/src/main/kotlin/dev/zacsweers/catchup/service/VisualServiceUi.kt
- app/src/main/kotlin/io/sweers/catchup/ui/activity/MainActivity.kt
- services/github/src/main/kotlin/io/sweers/catchup/service/github/GitHubTrendingParser.kt
Sort of related to this ancient issue https://github.com/ZacSweers/CatchUp/issues/102#issuecomment-366467389
https://github.com/ZacSweers/CatchUp/assets/1361086/f71d3999-b00c-4540-a56d-b41016cb07a8
> Add animated action items row

- README.md
Caused by the `app` to `app-scaffold` migration #1067
> Fix header image in README.md

- app-scaffold/src/main/kotlin/catchup/app/ui/activity/OrderServicesScreen.kt
Fixes #1357 
Before | After
:--: | :--:
> Call navigationBarsPadding on save Fab to add needed padding

- gradle/libs.versions.toml
- libraries/util/build.gradle.kts
- libraries/util/src/main/kotlin/catchup/util/network/AuthInterceptor.kt
- libraries/util/src/test/kotlin/catchup/util/AuthInterceptorTest.kt
Testing serialization + enabling its test
> Fixup auth interceptor
